(defun new (clname &rest coppie) 
	(let ((attributi (make-hash-table))
	      (prototipo (get-class-spec clname))
	     )
	     (progn 
		(or (check_args coppie) (error ""))
		(deep_copy (car prototipo) attributi)
		(init-slots (cons attributi clname) coppie T)
		(cons attributi clname)
	     )
	)
)
