(defparameter *classes-specs* (make-hash-table))

(defun add-class-spec (name class-spec)
	(setf (gethash name *classes-specs*) class-spec))
(defun get-class-spec (name)
	(gethash name *classes-specs*))

(defun deep_copy (table1 table2)
	(mapcar (lambda (name) 
		(setf (gethash name table2) 
			(gethash name table1))) 
		(gethash '__names__ table1)
	)
)

(defun init_names_list (hmap)
	(progn	(setf (gethash '__names__ hmap) '(__names__)))
		 hmap)
(defun init_hmaps (parent) 
	(let	((attributi (make-hash-table))
		(metodi (make-hash-table)))
		(if (null parent)
			(cons (init_names_list attributi) 
			(init_names_list metodi))
		;else
			(progn (deep_copy (car (get-class-spec parent)) 
					attributi)
			       (deep_copy (cdr (get-class-spec parent))
					metodi)
			       (cons attributi metodi)
			)
		)
	)
)

(defun has_member (hmap memname)
	(member memname (gethash '__names__ hmap))
)
